server:
  port: 8870
spring:
  application:
    name: dummy-service
eureka:
  instance:
      hostname: localhost
      port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
