server:
  port: 8871
spring:
  application:
    name: speed-service
eureka:
  instance:
      #hostname: 172.33.13.2
      hostname: 10.21.73.38
      port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
