#!/bin/sh
set -x
sudo docker rm -f dg-spring-client
sleep 2
sudo mvn clean install -Pdocker-build-image
sleep 2
#sudo mvn clean install -Pdocker-push-image
sudo docker run -it --name dg-spring-client dg-spring-client:latest
#mvn -Ddocker.username=jkong85 -Ddocker.password=19851208 docker:push

